default: &default
  adapter: postgresql
  pool: 5
  username: postgres
  password: postgres
  host: localhost

development:
  <<: *default
  database: diffi_hellman_development

test:
  <<: *default
  database: diffi_hellman_test
